#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Regex to check for exact pattern: [AJ_A1_00]: Your commit message
VALID_COMMIT_REGEX="^\[([A-Z]{2,3})_A[0-9]+_[0-9]{2}\]: .+$"

# Skip check for automated merge commits
if echo "$COMMIT_MSG" | grep -Eq "^Merge branch"; then
  exit 0
fi

if ! echo "$COMMIT_MSG" | grep -Eq "$VALID_COMMIT_REGEX"; then
  echo "Invalid commit message format."
  echo "--------------------------------------------------------"
  echo "Your message: \"$COMMIT_MSG\""
  echo "--------------------------------------------------------"
  echo "It must follow the convention: [Story_ID]: <Task Title>"
  echo "Example: [AJ_A1_01]: Complete header section with test cases"
  exit 1
fi

exit 0
